### PR TITLE
Add send form tutorial

### PR DESCRIPTION
**Pull request by MintoD**

### CODE REVIEW

**Comment by KygekDev** [comment]
**Dear @MintoD,**

As far as I know, PocketMine School has been left unmaintained for over 6 months as of writing this. If you want your edit to be live as soon as possible, consider **[submitting a pull request](https://github.com/KygekTeam/Pocketmine-School/pulls)** to KygekTeam's forked version of PocketMine School, which is currently maintained actively by KygekTeam. We will review your pull request as soon as possible.

**Thanks for your attention.**
**-- KygekDev**

**Review by IcyEndymion004 — APPROVED** [review]
Seems good

**Comment by KygekDev** [comment]
## UPDATE
#### Dear @MintoD,

PocketMine School is now alive again! We will merge this pull request right after #16 has been merged.

-- KygekDev

**Comment by KygekDev** [comment]
This PR will be closed because I've made such changes in https://github.com/PocketMine-School/Pocketmine-School/commit/ac2520c4a36ef352bde97a7a93d148182be6f5fa

**Pull request closed without merging**
